name: Bench

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  micro:
    name: Micro
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [ debug, release ]
    steps:
      - uses: actions/checkout@v2

      - name: micro_st
        run: ./scripts/run.py micro_st -b ${{matrix.build_type}} --iter 10

      - name: micro_mt
        run: ./scripts/run.py micro_mt -b ${{matrix.build_type}} --size 16 --iter 10

  leveldb:
    name: LevelDB
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: leveldb_tests
        run: ./scripts/run.py leveldb_tests

      - name: leveldb_ycsb
        run: |
          ./scripts/run.py leveldb_ycsb -- -f data/ycsb/a-load-1k.txt
          ./scripts/run.py leveldb_ycsb -- -f data/ycsb/a-run-1k.txt
          ./scripts/run.py leveldb_ycsb -- -f data/ycsb/b-load-1k.txt
          ./scripts/run.py leveldb_ycsb -- -f data/ycsb/b-run-1k.txt
          ./scripts/run.py leveldb_ycsb -- -f data/ycsb/c-load-1k.txt
          ./scripts/run.py leveldb_ycsb -- -f data/ycsb/c-run-1k.txt
          ./scripts/run.py leveldb_ycsb -- -f data/ycsb/d-load-1k.txt
          ./scripts/run.py leveldb_ycsb -- -f data/ycsb/d-run-1k.txt
          ./scripts/run.py leveldb_ycsb -- -f data/ycsb/e-load-1k.txt
          ./scripts/run.py leveldb_ycsb -- -f data/ycsb/e-run-1k.txt
          ./scripts/run.py leveldb_ycsb -- -f data/ycsb/f-load-1k.txt
          ./scripts/run.py leveldb_ycsb -- -f data/ycsb/f-run-1k.txt

  tpcc:
    name: SQLite
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: run
        run: |
          LD_PRELOAD=./build-release/libmadfs.so \
            sqlite3 tpcc.db '.read data/tpcc.sql'
          ./scripts/run.py tpcc_load -- -w 1
          ./scripts/run.py tpcc_start -- -w 4 -c 1 -t 10
