name: Bench

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "build type"
        required: true
        default: "release"
  pull_request:

jobs:
  micro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: micro_st
        run: BENCH_NUM_ITER=10 ./run micro_st ${{matrix.build_type}}

      - name: micro_mt
        run: BENCH_NUM_ITER=10 ./run micro_mt ${{matrix.build_type}}

      - name: micro_meta
        run: BENCH_NUM_ITER=10 ./run micro_meta ${{matrix.build_type}}

  leveldb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: leveldb_tests
        run: ./run leveldb_tests ${{matrix.build_type}}

      - name: ycsb
        run: ./scripts/bench_ycsb
