name: Bench

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "build type"
        required: true
        default: "release"
  pull_request:

jobs:
  micro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: micro
        run: ./run micro ${{matrix.build_type}}
        env:
          BENCH_NUM_ITER: 10

  leveldb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: leveldb_tests
        run: ./run leveldb_tests ${{matrix.build_type}}
      - name: ycsb
        run: ./scripts/bench_ycsb
