name: Bench

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  micro:
    name: Micro
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [ debug, release ]
    steps:
      - uses: actions/checkout@v2

      - name: micro_st
        run: ./run micro_st -b ${{matrix.build_type}} --iter 10

      - name: micro_mt
        run: ./run micro_mt -b ${{matrix.build_type}} --size 16 --iter 10

      - name: micro_meta
        run: ./run micro_meta -b ${{matrix.build_type}} --iter 10

  leveldb:
    name: LevelDB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: leveldb_tests
        run: ./run leveldb_tests

      - name: leveldb_ycsb
        run: |
          ./run leveldb_ycsb -- -f bench/ycsb-traces/a-load.txt
          ./run leveldb_ycsb -- -f bench/ycsb-traces/a-run.txt
          ./run leveldb_ycsb -- -f bench/ycsb-traces/b-load.txt
          ./run leveldb_ycsb -- -f bench/ycsb-traces/b-run.txt
          ./run leveldb_ycsb -- -f bench/ycsb-traces/c-load.txt
          ./run leveldb_ycsb -- -f bench/ycsb-traces/c-run.txt
          ./run leveldb_ycsb -- -f bench/ycsb-traces/d-load.txt
          ./run leveldb_ycsb -- -f bench/ycsb-traces/d-run.txt
          ./run leveldb_ycsb -- -f bench/ycsb-traces/e-load.txt
          ./run leveldb_ycsb -- -f bench/ycsb-traces/e-run.txt
          ./run leveldb_ycsb -- -f bench/ycsb-traces/f-load.txt
          ./run leveldb_ycsb -- -f bench/ycsb-traces/f-run.txt

  tpcc:
    name: SQLite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run
        run: |
          LD_PRELOAD=./build-release/libulayfs.so \
            sqlite3 tpcc.db '.read bench/tpcc.sql'
          ./run tpcc_load -- -w 1
          ./run tpcc_start -- -w 4 -c 1 -t 10
