name: Bench

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "build type"
        required: true
        default: "release"
  pull_request:

jobs:
  micro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: micro_st
        run: BENCH_NUM_ITER=10 ./run micro_st ${{matrix.build_type}}

      - name: micro_mt
        run: BENCH_NUM_ITER=10 ./run micro_mt ${{matrix.build_type}}

      - name: micro_meta
        run: BENCH_NUM_ITER=10 ./run micro_meta ${{matrix.build_type}}

  leveldb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: leveldb_tests
        run: ./run leveldb_tests ${{matrix.build_type}}

      - name: ycsb
        run: |
          ./run leveldb_ycsb -p="-f bench/ycsb-traces/a-load.txt"
          ./run leveldb_ycsb -p="-f bench/ycsb-traces/a-run.txt"
          ./run leveldb_ycsb -p="-f bench/ycsb-traces/b-load.txt"
          ./run leveldb_ycsb -p="-f bench/ycsb-traces/b-run.txt"
          ./run leveldb_ycsb -p="-f bench/ycsb-traces/c-load.txt"
          ./run leveldb_ycsb -p="-f bench/ycsb-traces/c-run.txt"
          ./run leveldb_ycsb -p="-f bench/ycsb-traces/d-load.txt"
          ./run leveldb_ycsb -p="-f bench/ycsb-traces/d-run.txt"
          ./run leveldb_ycsb -p="-f bench/ycsb-traces/e-load.txt"
          ./run leveldb_ycsb -p="-f bench/ycsb-traces/e-run.txt"
          ./run leveldb_ycsb -p="-f bench/ycsb-traces/f-load.txt"
          ./run leveldb_ycsb -p="-f bench/ycsb-traces/f-run.txt"
