name: Benchmark

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "build type"
        required: true
        default: "release"
  pull_request:

jobs:
  microbench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: bench
        run: ./run bench ${{matrix.build_type}}
        env:
          BENCH_NUM_ITER: 10

  leveldb-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: db_test
        run: ./run db_test ${{matrix.build_type}}
