name: Bench

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "build type"
        required: true
        default: "release"
  pull_request:

jobs:
  micro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: bench
        run: ./run bench ${{matrix.build_type}}
        env:
          BENCH_NUM_ITER: 10

  leveldb-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: leveldb_tests
        run: ./run leveldb_tests ${{matrix.build_type}} --prog_args="-DBTest.Randomized"
