name: Bench

on:
  pull_request:

env:
  build_type: release

jobs:
  micro:
    name: Microbenchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make ${{env.build_type}} \
          CMAKE_ARGS='-DULAYFS_BUILD_BENCH=ON' \
          BUILD_TARGETS='micro_st micro_mt micro_meta ulayfs'

      - name: micro_st
        run: BENCH_NUM_ITER=10 ./run micro_st ${{env.build_type}}

      - name: micro_mt
        run: BENCH_NUM_ITER=10 ./run micro_mt ${{env.build_type}}

      - name: micro_meta
        run: BENCH_NUM_ITER=10 ./run micro_meta ${{env.build_type}}

  leveldb:
    name: LevelDB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make ${{env.build_type}} \
          CMAKE_ARGS='-DULAYFS_BUILD_BENCH=ON' \
          BUILD_TARGETS='leveldb_tests leveldb_ycsb ulayfs'

      - name: leveldb_tests
        run: ./run leveldb_tests ${{env.build_type}}

      - name: leveldb_ycsb
        run: |
          ./run leveldb_ycsb ${{env.build_type}} -p="-f bench/ycsb-traces/a-load.txt"
          ./run leveldb_ycsb ${{env.build_type}} -p="-f bench/ycsb-traces/a-run.txt"
          ./run leveldb_ycsb ${{env.build_type}} -p="-f bench/ycsb-traces/b-load.txt"
          ./run leveldb_ycsb ${{env.build_type}} -p="-f bench/ycsb-traces/b-run.txt"
          ./run leveldb_ycsb ${{env.build_type}} -p="-f bench/ycsb-traces/c-load.txt"
          ./run leveldb_ycsb ${{env.build_type}} -p="-f bench/ycsb-traces/c-run.txt"
          ./run leveldb_ycsb ${{env.build_type}} -p="-f bench/ycsb-traces/d-load.txt"
          ./run leveldb_ycsb ${{env.build_type}} -p="-f bench/ycsb-traces/d-run.txt"
          ./run leveldb_ycsb ${{env.build_type}} -p="-f bench/ycsb-traces/e-load.txt"
          ./run leveldb_ycsb ${{env.build_type}} -p="-f bench/ycsb-traces/e-run.txt"
          ./run leveldb_ycsb ${{env.build_type}} -p="-f bench/ycsb-traces/f-load.txt"
          ./run leveldb_ycsb ${{env.build_type}} -p="-f bench/ycsb-traces/f-run.txt"

  tpcc:
    name: SQLite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run
        run: |
          LD_PRELOAD=./build-${{env.build_type}}/libulayfs.so \
            sqlite3 tpcc.db '.read bench/tpcc_sqlite/create_table.sql'
          ./run tpcc_load ${{env.build_type}} -p="-w 1"
          ./run tpcc_start ${{env.build_type}} -p="-w 4 -c 1 -t 10"
