name: CMake

on:
  push:
    branches: [ main ]
  pull_request:

env:
  BUILD_TYPE: debug

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.12
        with:
          extensions: 'h,cpp'
          clangFormatVersion: 12
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        working-directory: ${{github.workspace}}
        run: make ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build-${{env.BUILD_TYPE}}
        run: |
          ./test_rw
#          ./test_sync
