name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}

      - name: run clang-format
        run: clang-format -i -style=file **/*.cpp **/*.h **/*.h.in

      - uses: stefanzweifel/git-auto-commit-action@v4.12.0

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      matrix:
        build_type: [ debug, release, pmemcheck, asan, ubsan, msan, tsan ]
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make ${{matrix.build_type}} BUILD_TARGETS="ulayfs"

      - name: test_basic
        run: ./run test_basic ${{matrix.build_type}}

      - name: test_rw
        run: ./run test_rw ${{matrix.build_type}}

      - name: test_sync
        run: ./run test_sync ${{matrix.build_type}}
