name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          extensions: "h,h.in,cpp"
          clangFormatVersion: 10

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      matrix:
        build_type: [ debug, release, pmemcheck, asan, ubsan, msan ]
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make ${{matrix.build_type}} BUILD_ARGS="ulayfs"

      - name: test_basic
        run: ./run test_basic ${{matrix.build_type}}

      - name: test_rw
        run: ./run test_rw ${{matrix.build_type}}

      - name: test_sync
        run: ./run test_sync ${{matrix.build_type}}
