name: Format

on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}

      - name: run clang-format
        run: clang-format -i -style=file **/*.cpp **/*.h **/*.h.in

      - uses: stefanzweifel/git-auto-commit-action@v4.12.0
