name: LevelDB

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "uLayFS build type"
        required: true
        default: "release"

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: db_test
        run: ./run db_test ${{matrix.build_type}}
