name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    strategy:
      matrix:
        build_type: [ debug, release, relwithdebinfo, pmemcheck, asan, ubsan, msan, tsan ]
    name: ${{matrix.build_type}}
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make ${{matrix.build_type}}

      - name: test_basic
        run: ./scripts/run.py test_basic -b ${{matrix.build_type}}

      - name: test_rw
        run: ./scripts/run.py test_rw -b ${{matrix.build_type}}

      - name: test_sync
        run: ./scripts/run.py test_sync -b ${{matrix.build_type}}

      - name: test_gc
        if: ${{matrix.build_type}} != 'pmemcheck'
        run: ./scripts/run.py test_gc -b ${{matrix.build_type}}
