name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      matrix:
        build_type: [ debug, release, pmemcheck, asan, ubsan, msan, tsan ]
    name: ${{matrix.build_type}}
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make ${{matrix.build_type}} BUILD_TARGETS="ulayfs"

      - name: test_basic
        run: ./run test_basic ${{matrix.build_type}}

      - name: test_rw
        run: ./run test_rw ${{matrix.build_type}}

      - name: test_sync
        run: ./run test_sync ${{matrix.build_type}}
